CoffeeClub/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Coffee_Club.Model;
using System.Text;
using System.Net.Mail;
using System.Configuration;

namespace Coffee_Club.Controllers
{
    public class ContactController : SurfaceController
    {
        [ChildActionOnly]
        public ActionResult ContactForm()
        {
            // In case you need it...
            //var currentNode = Umbraco.TypedContent(UmbracoContext.PageId.GetValueOrDefault());

            var model = new ContactModel();
            return PartialView("ContactForm", model);
        }


        [HttpPost]
        public ActionResult ContactForm(ContactModel model)
        {
            if (ModelState.IsValid)
            {
                var sb = new StringBuilder();
                sb.AppendFormat("<p><b>Name:</b> {0}</p>", model.Name);
                sb.AppendFormat("<p><b>Email:</b> {0}</p>", model.Email);
                sb.AppendFormat("<p><b>Phone:</b> {0}</p>", model.Phone);
                sb.AppendFormat("<p><b>Subject:</b> {0}</p>", model.Subject);
                sb.AppendFormat("<p><b>Message:</b> {0}</p>", model.Message);
               
               

                var Sender = model.Email;
                MailMessage mailMessage = new MailMessage(Sender, "aashish.bhurtel@yahoo.com");
                mailMessage.IsBodyHtml = true;
                mailMessage.Body = sb.ToString();
                mailMessage.Subject = model.Subject;               
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Send(mailMessage);

                TempData["Success"] = "Thanks for your message.";
                return RedirectToUmbracoPage(model.RedirectPage);
            }
            return this.RedirectToCurrentUmbracoPage();
        }
    }
}

CoffeeClub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Models;

namespace Coffee_Club.Controllers
{
    public class HomeController : Umbraco.Web.Mvc.RenderMvcController
    {
        public override ActionResult Index(RenderModel model)
        {
            //Do some stuff here, then return the base method

            return base.Index(model);
        }

    }
}

CoffeeClub/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.Parent.topLevelImage);
}

@*@CurrentPage.GetGridHtml("content", "fanoe")*@

<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
<div class="container">
    <div id="menuLogoTop">
          @*<h1>@CurrentPage.Parent.name.ToUpper()</h1>*@
        <h1>ABOUT US</h1>
    </div>
</div>
</div>

<div id="orangeTab" style="height:50px; padding-top:14px;">
    
        <h3>@CurrentPage.name.ToUpper()</h3>
   
</div>

<div class="container">
    <br />
   
    <div class="text-left" style="text-align:justify">
        @CurrentPage.descriptionParagraph
    </div>
    <br />
    @if (!string.IsNullOrEmpty(CurrentPage.youtubeUrl))
    {
        <div id="UVideo" class="text-left">
        </div>
    }
</div>
@{Html.RenderPartial("_FooterBlock");}

<script type="text/javascript">

    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = false;
    ga.src = 'http://www.youtube.com/player_api';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
    var done = false;
    var player;

    function onYouTubePlayerAPIReady() {
        var url = '@CurrentPage.youtubeUrl';
        var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
        var Id = '';
        var match = url.match(regExp);
        if (match && match[7].length == 11) {
            Id = match[7];
        } else {
            //alert("Could not extract video ID.");
        }

        player = new YT.Player('UVideo', {
           // height: '390',
            width: '100%',
            videoId: Id,
            playerVars: {
                controls: 0,
                disablekb: 1,
                showinfo:0
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }
    function onPlayerReady(evt) {
        //console.log('onPlayerReady', evt);

    }
    function onPlayerStateChange(evt) {
        //console.log('onPlayerStateChange', evt);
        //if (evt.data == YT.PlayerState.PLAYING && !done) {
        //    setTimeout(stopVideo, 6000);
        //    done = true;
        //}
    }

    function stopVideo() {
        //console.log('stopVideo');
        //player.stopVideo();
    }



</script>

CoffeeClub/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
    var home = @CurrentPage.Site();
}

@if (TempData["Captcha2"] != null)
{
    <script>
        alert("@TempData["Captcha2"]");
    </script>
}

@if (TempData["Captcha1"] != null)
{
    <script>
        alert("@TempData["Captcha1"]");
    </script>
}


<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div class="container">
        <div id="menuLogoTop">
            <h1>@CurrentPage.name.ToUpper()</h1>
        </div>
    </div>
</div>

<div style="background-color:#fefefe;">
    <div role="tabpanel">
        <div id="orangeTabStore">
            <div class="container">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist" id="tabHolder">
                    <li id="tabStore" class="active" style="width:50%"> <a href="#storeDiv" role="tab" data-toggle="tab">GENERAL ENQUIRY</a></li>
                    <li id="tabPhoto" style="width:50%"><a href="#photoDiv" role="tab" data-toggle="tab">YOUR FEEDBACK</a></li>
                </ul>
            </div>
        </div>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="storeDiv">
                <div class="container" id="storeDetailContainer" style="">
                    @{
                        if (TempData["Success"] != null)
                        {
                            <div class="alert alert-success alert-block fade in" id="successAlert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <p>@TempData["Success"]</p>
                            </div>
                        }
                    }

                    <div class="col-md-7">
                         @if (home.HasValue("contactInfoText"))
                         {
                             <p style="padding-left:10px;">@home.contactInfoText</p>
                         }

                        @{Html.RenderAction("ContactForm", "Contact");  }
                    </div>


                    <div class="col-md-5">
                        <div class="row" style="padding:20px;">
                            <div class="col-md-12">
                                @CurrentPage.franchisingContact
                            </div>
                        </div>
                    </div>  
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="photoDiv">
                <div class="container" style="padding: 30px 0px;">
                    <div class="">
                        @if (home.HasValue("feedbackInfoText"))
                        {
                            <p style="padding-left:10px;">@home.feedbackInfoText</p>
                        }
                        @{Html.RenderAction("FeedbackForm", "Contact");  }
                    </div>
                  
                </div>
            </div>

        </div>@*This is End of tab content block*@
    </div>@*This is the end of tabpanel role*@
</div>

@{Html.RenderPartial("_FooterBlock");}

@section Javascript
{
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>
@*<link href="~/css/jquery-ui.min.css" rel="stylesheet" />
<script src="~/js/jquery-ui.min.js"></script>*@  


 <script type="text/javascript">
    $(document).ready(function () {
        //$("#date").datepicker({ dateFormat: 'dd-mm-yy' });

        $("#feedbackFormButton").click(function (e) {

            var name = $('#name2').val();
            var email = $('#email2').val();
            var phone = $('#phone2').val();
            var captchaFeedbackText = $('#tbCaptcha2').val();    

            if (name.length == 0 && email.length == 0 && phone.length == 0) {
                alert("Some of the required fields are empty");
                e.preventDefault();
                return false;
            }

            if (name.length == 0) {
                alert("Name is required.");
                e.preventDefault();
                return false;
            }

            if (phone.length == 0) {
                alert("Phone is required.");             
                e.preventDefault();
                return false;
            }
           
            if ($("#visitedTime").val() === "") {
                alert("Visited time is required.");
                e.preventDefault();
                return false;
            }


            if ($("#date").val() === "") {
                alert("Visited date is required.");
                e.preventDefault();
                return false;
            }
            
            if ($("#storeSelect").val() === "") {
                alert("Please select the visited store.");
                e.preventDefault();
                return false;
            }


            if (email != 0) {
                if (isValidEmailAddress(email)) {
                    $("#email2").css({
                        "background-color": "none"
                    });
                } else {
                    $("#email2").css({
                        "background-color": "#DCB286"
                    });
                    alert("Invalid Email");
                    return false;
                }
            } else {
                $("#email2").css({
                    "background-color": "none"
                });
            }


            e.preventDefault();
            $.ajax({
                type: 'GET',
                url: '/umbraco/surface/Contact/CaptchaTextCompare',
                data: { isContact: false, captchaText: captchaFeedbackText },
                dataType: "json",
                cache: false,
                success: function (data) {
                    if (!data.success) {
                        alert("Captch code did not match....");

                    } else {
                        $('#feedbackForm').off('submit')
                        $('#feedbackForm').submit();
                    }
                },
                error: function (data) {
                    alert("Something went wrong Please try again later");
                }
            });
        });


        $("#email2").keyup(function () {
            $("#email2").css({
                "background-color": "none"
            });
        });

     

        @*@if (Request.Url.ToString().IndexOf("feedback", StringComparison.OrdinalIgnoreCase) != -1)
        {
            <text>
                 $("#tabStore").removeClass("active");
                 $("#tabPhoto").addClass("active");
                 $("#storeDiv").removeClass("active");
                 $("#photoDiv").addClass("active");
                 $("#tabHolder").hide();
           </text>
        }*@



    });

    function isValidEmailAddress(emailAddress) {
        var pattern = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
        return pattern.test(emailAddress);
    }


    </script>
}

CoffeeClub/Views/CustomAction.cshtml
<div style="height:200px">


</div>

CoffeeClub/Views/FeedbackForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
    var home = @CurrentPage.Site();
}

@if (TempData["Captcha2"] != null)
{
    <script>
        alert("@TempData["Captcha2"]");
    </script>
}

<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div class="container">
        <div id="menuLogoTop">
            <h1>@CurrentPage.name.ToUpper()</h1>
        </div>
    </div>
</div>

<div style="background-color:#fefefe;">
    <div role="tabpanel">
        <div id="orangeTabStore">
            <div class="container">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist" id="tabHolder">
                    <li id="tabStore" class="active" style="width:50%"> <a href="#storeDiv" role="tab" data-toggle="tab">YOUR FEEDBACK</a></li>
                   
                </ul>
            </div>
        </div>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="storeDiv">
                <div class="container" id="storeDetailContainer" style="">
                    @{
                        if (TempData["Success"] != null)
                        {
                            <div class="alert alert-success alert-block fade in" id="successAlert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <p>@TempData["Success"]</p>
                            </div>
                        }
                    }

                    <div class="">
                        @if (home.HasValue("feedbackInfoText"))
                        {
                            <p style="padding-left:10px;">@home.feedbackInfoText</p>
                        }
                        @{Html.RenderAction("FeedbackForm", "Contact");  }
                    </div>                  
                </div>
            </div>
          

        </div>@*This is End of tab content block*@
    </div>@*This is the end of tabpanel role*@
</div>

@{Html.RenderPartial("_FooterBlock");}

@section Javascript
{
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
    @*<link href="~/css/jquery-ui.min.css" rel="stylesheet" />
        <script src="~/js/jquery-ui.min.js"></script>*@


    <script type="text/javascript">
        $(document).ready(function () {
            //$("#date").datepicker({ dateFormat: 'dd-mm-yy' });

            $("#feedbackFormButton").click(function (e) {

                var name = $('#name2').val();
                var email = $('#email2').val();
                var phone = $('#phone2').val();
                var captchaFeedbackText = $('#tbCaptcha2').val();               

                if (name.length == 0 && email.length == 0) {
                    alert("Some of the required fields are empty");
                    e.preventDefault();
                    return false;
                }

                if (name.length == 0) {
                    alert("Name is required.");
                    e.preventDefault();
                    return false;
                }

                if (phone.length == 0) {
                    alert("Phone is required.");
                    e.preventDefault();
                    return false;
                }

                if ($("#visitedTime").val() === "") {
                    alert("Visited time is required.");
                    e.preventDefault();
                    return false;
                }


                if ($("#date").val() === "") {
                    alert("Visited date is required.");
                    e.preventDefault();
                    return false;
                }

                if ($("#storeSelect").val() === "") {
                    alert("Please select the visited store.");
                    e.preventDefault();
                    return false;
                }

                if (email != 0) {
                    if (isValidEmailAddress(email)) {
                        $("#email2").css({
                            "background-color": "none"
                        });
                    } else {
                        $("#email2").css({
                            "background-color": "#DCB286"
                        });
                        alert("Invalid Email");
                        return false;
                    }
                } else {
                    $("#email2").css({
                        "background-color": "none"
                    });
                }

                e.preventDefault();
                $.ajax({
                    type: 'GET',
                    url: '/umbraco/surface/Contact/CaptchaTextCompare',
                    data: { isContact: false, captchaText: captchaFeedbackText },
                    dataType: "json",
                    cache: false,
                    success: function (data) {
                        if (!data.success) {
                            alert("Captch code did not match....");

                        } else {
                            $('#feedbackForm').off('submit')
                            $('#feedbackForm').submit();
                        }
                    },
                    error: function (data) {
                        alert("Something went wrong Please try again later");
                    }
                });
            });


            $("#email2").keyup(function () {
                $("#email2").css({
                    "background-color": "none"
                });
            });     

            @*@if (Request.Url.ToString().IndexOf("feedback", StringComparison.OrdinalIgnoreCase) != -1)
        {
            <text>
                 $("#tabStore").removeClass("active");
                 $("#tabPhoto").addClass("active");
                 $("#storeDiv").removeClass("active");
                 $("#photoDiv").addClass("active");
                 $("#tabHolder").hide();
           </text>
        }*@



        });

        function isValidEmailAddress(emailAddress) {
            var pattern = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
            return pattern.test(emailAddress);
        }


    </script>
}

CoffeeClub/Views/FirstHome.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

Content Goes here

CoffeeClub/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var srcCentralLogo = Umbraco.Media(CurrentPage.centrallogohomepage);
    var currentTime = DateTime.Now.TimeOfDay;
    var BreakfastTime = new TimeSpan(11, 59, 59);
    var LaunchTime = new TimeSpan(16, 59, 59);
    var DinnerTime = new TimeSpan(23, 59, 59);
    var MidNight = new TimeSpan(00, 00, 00);   
      
}

@*@CurrentPage.GetGridHtml("content", "fanoe")*@	

<div style="text-align: center; color: white; height: 100%;">
    <div class=" hidden-sm hidden-xs" style="width:100%; position:absolute; top: 30%;left: 50%;z-index:90;   margin: 0px 0 0 -50%">
       
        <div class="row" style="margin-bottom:20px;">
            <h1 style="">WELCOME TO</h1>
            <img src="@srcCentralLogo.Url" alt="TheCoffeeClub" style="width:25%;" />
        </div>


        @{Html.RenderPartial("_CenterBlockForHomePage");}
    </div>


    @{
        if (currentTime < BreakfastTime && currentTime > MidNight)
        {
            if (Model.Content.HasValue("largehomeimage"))
            {
                var imageIdList = Model.Content.GetPropertyValue<string>("largehomeimage").Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
                var imageCollection = Umbraco.TypedMedia(imageIdList).Where(x => x != null);
                <div class="fadein">
                    @foreach (var image in imageCollection)
                    {
                        <img src=@image.Url alt="@image.Name" />
                    }
                </div>
            }
        }
        if (currentTime < LaunchTime && currentTime > BreakfastTime) 
        {
            if (Model.Content.HasValue("launchTimePhotos"))
            {
                var imageIdList = Model.Content.GetPropertyValue<string>("launchTimePhotos").Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
                var imageCollection = Umbraco.TypedMedia(imageIdList).Where(x => x != null);
                <div class="fadein">
                    @foreach (var image in imageCollection)
                    {
                        <img src=@image.Url alt="@image.Name" style="" />
                    }
                </div>
            }
        }
        if (currentTime < DinnerTime && currentTime > LaunchTime)
        {
            if (Model.Content.HasValue("dinnerTimePhotos"))
            {
                var imageIdList = Model.Content.GetPropertyValue<string>("dinnerTimePhotos").Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
                var imageCollection = Umbraco.TypedMedia(imageIdList).Where(x => x != null);
                <div class="fadein">
                    @foreach (var image in imageCollection)
                    {
                        <img src=@image.Url alt="@image.Name" />
                    }
                </div>
            }
        }        
    }
 
</div>
<div class="visible-xs visible-sm" style="position:relative; top:0px;" >
    @{Html.RenderPartial("_FooterBlock");}
    <div class="container">
        <img src="@srcCentralLogo.Url" alt="TheCoffeeClub" style="width:100%" />
    </div>
    
</div>


<style>
     /*.fadein { width:100%; height:100% }*/
    /*.fadein img { width:100%;}*/
    .fadein{
        height: 100%;
    }
    
    .fadein img {
        width: 100%
    }

</style>

<script>
    $("document").ready(function () {
        $('.fadein img:gt(0)').hide();
        setInterval(function () {
            $('.fadein :first-child').fadeOut(1000)
               .next('img').fadeIn(1000)
               .end().appendTo('.fadein');
        }, 50000);
    });
</script>

CoffeeClub/Views/MacroPartials/ContactForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
	@Html.Action("ContactForm", "Contact")

CoffeeClub/Views/MenuDetail.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "SubMenu.cshtml";
    var home = @CurrentPage.Site();
}

<link href="~/css/flexslider.css" rel="stylesheet" />


<div style="background-color:#fefefe;">
  
    <div id="orangeTabMenu">
        <div class="container">
            <!-- Nav tabs -->
            <ul>
                @foreach (var item in CurrentPage.Parent.Children)
                {
                    if (item.Url == CurrentPage.Url)
                    {
                        			
						@*NEW SCRIPT - ADDED BY JAN SOBIDA 07-24-2019*@
						@*BEGIN*@
						if (@item.Name != "VEGAN MENU")
						{
							<li><a class="activeMenu" href="@item.Url">@item.Name</a></li>
						}
						@*END*@
									
									
						@*OLD SCRIPT - REMOVED BY JAN SOBIDA 07-24-2019*@
						@*BEGIN*@
						@*<li><a class="activeMenu" href="@item.Url">@item.Name</a></li>*@
						@*END*@

                    }
                    else
                    {
                       	@*NEW SCRIPT - ADDED BY JAN SOBIDA 07-24-2019*@
						@*BEGIN*@
						if (@item.Name != "VEGAN MENU")
						{
							<li> 
								<a href="@item.Url">@item.Name</a>
							</li>
						}
						@*END*@
									
									
						@*OLD SCRIPT - REMOVED BY JAN SOBIDA 07-24-2019*@
						@*BEGIN*@
						@*<li> 
                            <a href="@item.Url">@item.Name</a>
                        </li>*@
						@*END*@
                    }
                }
            </ul>
        </div>
    </div>

  
  
</div>

<div class="container text-center" style="margin-top:50px;">    
    
    @CurrentPage.menudescription
  
    @{
        if (home.HasValue("restaurantMenuUpload") && ((CurrentPage.Name.Contains("MAINS")) ? true : false))
        {

            <div class="downloadMenu">
                <a class="downloadButton" target="_blank" href="@home.restaurantMenuUpload" > DOWNLOAD OUR RESTAURANT MENU </a>
            </div>
        }
        else
        {
            if (home.HasValue("menuUpload"))
            {
                <div class="downloadMenu">
                    <a class="downloadButton" target="_blank" href="@home.menuUpload"> DOWNLOAD OUR CAFE MENU </a>
                </div>

            }
        }
}
    <br />
  
</div>


<div class="container">
    <hr />
    @*<div class="flexslider">
        <ul class="slides">
            @foreach (var item in CurrentPage.Children)
            {
                var photo = Umbraco.Media(item.photo);
                <li data-thumb="@photo.Url" style="padding:10px;">
                    <img  style="" src="@photo.Url" /><div class='flex-caption text-center'> <br /><h3>@item.Name</h3> <br /> @item.description</div>
                </li>
            }     
        </ul>
    </div>*@



    <div id="slider" class="flexslider" style="margin-bottom:5px;" >
        <ul class=" slides">
        @foreach (var item in CurrentPage.Children)
        {
            var photo = Umbraco.Media(item.photo);
            <li>
                <img style="width:80%; margin:auto;" src="@photo.Url" /><div class='flex-caption text-center' style="line-height:18px;"> <br /><h3 style="margin-bottom: 3px; text-align:center; ">@item.Name</h3> @item.description</div>
            </li>
        }

        </ul>
    </div>

    <div id="carousel" class="flexslider hidden-xs">
        <ul class="slides">
            @foreach (var item in CurrentPage.Children)
            {
                var photo = Umbraco.Media(item.photo);
                <li style="height: 143px; overflow:hidden">
                    <img  style="padding-right:5px; " src="@photo.Url" />
                </li>
            }     
        </ul>
    </div>


</div>

@*This is footer block.Copy this content for each template*@

 <div style="">
    @{Html.RenderPartial("_FooterBlock");}
</div>

@section Javascript
{
<script src="~/js/jquery.flexslider-min.js"></script>
<script>
        
    $(document).ready(function () {  
       
        $('#carousel').flexslider({
            animation: "slide",
            controlNav: false,
            animationLoop: false,
            slideshow: false,
            itemWidth: 210,
            itemMargin: 5,
            asNavFor: '#slider',
            smoothHeight: true

           
        });

        $('#slider').flexslider({
            animation: "slide",
            controlNav: false,
            animationLoop: true,
            slideshowSpeed: 5000,
            slideshow: true,
            sync: "#carousel",
            smoothHeight: true,
            touch: true,
        });


       

    });

    var value1 = $(".checkMenu").attr("href");
    if(value1 == "@CurrentPage.Url" )
    {
       highLight(menuid)
    }
    function highLight(menuid) {
        $('.checkMenu').addClass("current-menu");
    }
</script>

}

<style>


</style>

@*<div style="background-color:#fefefe;height:75px;">
    <div role="tabpanel">
        <div id="orangeTab">
            <div class="container">
                
                <ul class="nav nav-tabs" role="tablist">
                    @foreach (var item in CurrentPage.Parent.Children)
                    {
                        <li role="presentation" class="@(item.Name == CurrentPage.Name ? "active" : "")">
                            <a href="@item.Url" aria-controls="@item.Name" role="tab">@item.Name</a>
                        </li>

                    }
                </ul>
            </div>
        </div>
    </div>
</div>*@

CoffeeClub/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

CoffeeClub/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

CoffeeClub/Views/Popup.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

CoffeeClub/Views/TabItems.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}